/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertStudentButton = new javax.swing.JButton();
        InsertResultButton = new javax.swing.JButton();
        ListStudentButton = new javax.swing.JButton();
        ListStudentResultButton = new javax.swing.JButton();
        UpdateMarksButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InsertStudentButton.setText("INSERT STUDENT");
        InsertStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 220, 48));

        InsertResultButton.setText("INSERT RESULT");
        InsertResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertResultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, 46));

        ListStudentButton.setText("LIST OF STUDENT");
        ListStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ListStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 220, 52));

        ListStudentResultButton.setText("LIST OF STUDENT RESULT");
        ListStudentResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListStudentResultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ListStudentResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 220, 47));

        UpdateMarksButton.setText("UPDATE STUDENT MARKS");
        UpdateMarksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMarksButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateMarksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 220, 50));

        LogoutButton.setText("LOGOUT");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolPic1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1000, -450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertResultButtonActionPerformed
            InsertResult frame = new InsertResult();
            frame.setVisible(true); 
            frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_InsertResultButtonActionPerformed

    private void ListStudentResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListStudentResultButtonActionPerformed
        // TODO add your handling code here:
        ListofResult frame = new ListofResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_ListStudentResultButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "You sure you want to logout?", "Submit", JOptionPane.YES_NO_OPTION);
        
        if(response == 0){
            setVisible(false);
            HOME frame = new HOME();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ListStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListStudentButtonActionPerformed
        // TODO add your handling code here:
            ListofStudent frame = new ListofStudent();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_ListStudentButtonActionPerformed

    private void InsertStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertStudentButtonActionPerformed
            InsertStudent frame = new InsertStudent();
            frame.setVisible(true); 
            frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_InsertStudentButtonActionPerformed

    private void UpdateMarksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMarksButtonActionPerformed
        // TODO add your handling code here:
        UpdateResult frame = new UpdateResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateMarksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertResultButton;
    private javax.swing.JButton InsertStudentButton;
    private javax.swing.JButton ListStudentButton;
    private javax.swing.JButton ListStudentResultButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton UpdateMarksButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
