/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ConnectionProvider.ConnectionProviderCode;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;

/**
 *
 * @author USER
 */
public class InsertStudent extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public InsertStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        GenderComboField = new javax.swing.JComboBox<>();
        CourseComboField = new javax.swing.JComboBox<>();
        BranchComboField = new javax.swing.JComboBox<>();
        NameTextField = new javax.swing.JTextField();
        RollNoTextField = new javax.swing.JTextField();
        FatherNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ROLL NO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("GENDER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("FATHER NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("COURSE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("BRANCH");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        GenderComboField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenderComboField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "TRANSGENDER" }));
        GenderComboField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderComboFieldActionPerformed(evt);
            }
        });
        getContentPane().add(GenderComboField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, -1));

        CourseComboField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CourseComboField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BTech", "BE" }));
        getContentPane().add(CourseComboField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 120, -1));

        BranchComboField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BranchComboField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELECTRONICS", "CIVIL", "MECHANICAL", "ELECTRICAL", "COMPUTER" }));
        BranchComboField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchComboFieldActionPerformed(evt);
            }
        });
        getContentPane().add(BranchComboField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 120, -1));
        getContentPane().add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 120, -1));
        getContentPane().add(RollNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 120, -1));

        FatherNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FatherNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 120, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolPic1.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(600, 450));
        jLabel7.setMinimumSize(new java.awt.Dimension(600, 450));
        jLabel7.setPreferredSize(new java.awt.Dimension(600, 450));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-990, -560, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolPic2.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(new java.awt.Dimension(600, 450));
        jLabel8.setMinimumSize(new java.awt.Dimension(600, 450));
        jLabel8.setPreferredSize(new java.awt.Dimension(600, 450));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -200, 790, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BranchComboFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchComboFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchComboFieldActionPerformed

    private void GenderComboFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderComboFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderComboFieldActionPerformed

    private void FatherNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String name = NameTextField.getText();
        String rollNo = RollNoTextField.getText();
        String gender = (String)GenderComboField.getSelectedItem();
        String fatherName = FatherNameTextField.getText();
        String course = (String)CourseComboField.getSelectedItem();
        String branch = (String)BranchComboField.getSelectedItem();
        
            try{
                 Connection con = ConnectionProviderCode.getcon();
                 Statement st = con.createStatement();
                 st.executeUpdate("insert into student values('"+ name + "', '" + rollNo +"', '"+ gender +"', '"+ fatherName +"', '"+ course +"', '"+ branch +"')");
                 JOptionPane.showMessageDialog(null, "Insertion Successful");
                 setVisible(false);
                 InsertStudent frame = new InsertStudent();
                 frame.setVisible(true);
                 frame.setLocationRelativeTo(null);
                }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null, e.toString());
             }

    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit", "submit", JOptionPane.YES_NO_OPTION);
        
        if(response ==0 ){
            setVisible(false);  
        }
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BranchComboField;
    private javax.swing.JComboBox<String> CourseComboField;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField FatherNameTextField;
    private javax.swing.JComboBox<String> GenderComboField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField RollNoTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
